### ISSUE TITLE
first element missing

### ISSUE THREAD

**Issue by everton15m** [Karumi/HeaderRecyclerView#9] opened 2015-09-23 23:17 UTC
has anyone noticed that the list is one item short when using the headerview? 
It might be me but I can not see all my items unless I add a dummy item at index 0 of my list.
Can anyone provide a solution?
Thank you

**Comment by pedrovgs** [comment] 2015-09-28 18:14
@Serchinastico @flipper83 can you take a look this week? This bug seems weird but maybe we can review if we've missing any test checking this.

**Comment by Serchinastico** [comment] 2015-09-28 23:10
@everton15m, can you share a snippet with your HeaderRecyclerView set up? I can't reproduce what you said in the latest version.

**Comment by everton15m** [comment] 2015-09-29 09:52
``` java
public class ProductsFragment extends BaseFragment {
    public final static String ARG_POSITION = "position";
    private static final String TAG = ProductsFragment.class.getSimpleName();
    String mCurrentKey = "";
    private GridLayoutManager mLayoutManager;
    private RecyclerView mRecyclerView;
    private ProductsAdapter mAdapter;
    private List<Product> products = new ArrayList<>();
    private Category currentCategory;
    private OnItemClickListener.OnItemClickCallback onItemClickCallback = new OnItemClickListener.OnItemClickCallback() {
        @Override
        public void onItemClicked(View view, int position) {
            Intent intent = new Intent(getActivity(), ProductDetailActivity.class);
            intent.putExtra(ProductDetailActivity.PRODUCT_KEY, products.get(position - 1).getProduct_name());//position-1, because we added dummy data at index 0
            Translation trans = Util.getTRanslation(currentCategory.getTrans(), PersistentUtil.getSavedLanguage(getActivity()));
            intent.putExtra(ProductDetailActivity.PARENT_NAME_KEY, trans.getName());//add the category name so we do not make another query in the next screen
            startActivity(intent);
            //mCallback.onCategorySelected(position);
        }
    };
    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        //        if (savedInstanceState != null) {
        mCurrentKey = getArguments().getString(ARG_POSITION);
//        }
        try {
            currentCategory = realm.where(Category.class)
                    .equalTo("category_name", mCurrentKey).findFirst();
            products = currentCategory.getProducts();
            products.add(0, new Product());//add dummy element because of buggy library
        } catch (Exception e) {
            LogService.err(TAG, "Could not find any products asociated with this category");
        }
    }
    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {
        // If activity recreated (such as from screen rotate), restore
        // the previous article selection set by onSaveInstanceState().
        // This is primarily necessary when in the two-pane layout.
        View v = inflater.inflate(R.layout.layout_fragment_categories, container, false);
        mRecyclerView = (RecyclerView) v.findViewById(R.id.recycler_view_cat);
        mAdapter = new ProductsAdapter(products, getActivity(), onItemClickCallback);
        mLayoutManager = new GridLayoutManager(getActivity(), 2);
        HeaderSpanSizeLookup headerSpanSizeLookup = new HeaderSpanSizeLookup(mAdapter, mLayoutManager);
        mLayoutManager.setSpanSizeLookup(headerSpanSizeLookup);
        mRecyclerView.setLayoutManager(mLayoutManager);
        //mRecyclerView.setHasFixedSize(true);
        mAdapter.setHeader(currentCategory);
        mAdapter.setItems(products);
        //
        mRecyclerView.setAdapter(mAdapter);
        // Inflate the layout for this fragment
        return v;
    }
    @Override
    public void onLanguageChanged(String code) {
    }
    // The container Activity must implement this interface so the frag can deliver messages
    public interface OnProductSelected {
        /**
         * Called by CategoriesFragment when a list item is selected
         */
        public void onProductSelected(int position);
    }
}
```

and the adaptor is :

``` java
public class ProductsAdapter extends HeaderRecyclerViewAdapter<RecyclerView.ViewHolder,Category,Product,Category> {
    private static final String TAG = ProductsAdapter.class.getSimpleName();
    private List<Product> mItems;
    private Context mContext;
    private OnItemClickListener.OnItemClickCallback onItemClickCallback;
    public ProductsAdapter(List<Product> mItems, Context ctx, OnItemClickListener.OnItemClickCallback onItemClickCallback) {
        super();
        this.mItems = mItems;
        this.onItemClickCallback = onItemClickCallback;
        mContext = ctx;
    }
    @Override
    protected RecyclerView.ViewHolder onCreateHeaderViewHolder(ViewGroup viewGroup, int i) {
        View v = LayoutInflater.from(viewGroup.getContext())
                .inflate(R.layout.item_grid_recyclerview, viewGroup, false);
        ProductViewHolder viewHolder = new ProductViewHolder(v);
        return viewHolder;
    }
    @Override
    protected RecyclerView.ViewHolder onCreateItemViewHolder(ViewGroup viewGroup, int i) {
        View v = LayoutInflater.from(viewGroup.getContext())
                .inflate(R.layout.item_grid_recyclerview, viewGroup, false);
        ProductViewHolder viewHolder = new ProductViewHolder(v);
        return viewHolder;
    }
    @Override
    protected RecyclerView.ViewHolder onCreateFooterViewHolder(ViewGroup viewGroup, int i) {
        return null;//we do not need footer
    }
    @Override
    protected void onBindHeaderViewHolder(RecyclerView.ViewHolder viewHolder, int i) {
        Category category = getHeader();
        if(category==null)
        {
            LogService.err(TAG,"Error no header received");
            return;
        }
        ProductViewHolder productViewHolder= (ProductViewHolder) viewHolder;
        if (category != null && category.getTrans() != null) {
            Translation trans = Util.getTRanslation(category.getTrans(), PersistentUtil.getSavedLanguage(mContext));
            productViewHolder.tvDescription.setText(trans.getName());
            Glide.with(mContext).load(category.getImage_url()).diskCacheStrategy(DiskCacheStrategy.ALL).into(productViewHolder.imgThumbnail);
        }
    }
    @Override
    protected void onBindItemViewHolder(RecyclerView.ViewHolder viewHolder, int i) {
        Product item = getItem(i);
        ProductViewHolder productViewHolder= (ProductViewHolder) viewHolder;
        if (item != null && item.getTrans() != null) {
            Translation trans = Util.getTRanslation(item.getTrans(), PersistentUtil.getSavedLanguage(mContext));
            if(trans!=null)
            productViewHolder.tvDescription.setText(trans.getName());
            Glide.with(mContext).load(item.getImage_url()).diskCacheStrategy(DiskCacheStrategy.ALL).into(productViewHolder.imgThumbnail);
        }
        productViewHolder.imgThumbnail.setOnClickListener(new OnItemClickListener(i, onItemClickCallback));
    }
    @Override
    protected void onBindFooterViewHolder(RecyclerView.ViewHolder viewHolder, int i) {
    }
    class ProductViewHolder extends RecyclerView.ViewHolder {
        public ImageView imgThumbnail;
        public TextView tvDescription;
        public ProductViewHolder(View itemView) {
            super(itemView);
            imgThumbnail = (ImageView) itemView.findViewById(R.id.img_thumbnail);
            tvDescription = (TextView) itemView.findViewById(R.id.tv_species);
        }
    }
}
```

**Comment by Serchinastico** [comment] 2015-09-30 22:58
I've been doing some research and, as much as I try, I can't reproduce the bug you detail. I'm using the latest version of the library, that is 1.0.3, and executing a very similar code to yours ([gist](https://gist.github.com/Serchinastico/7363c8a722c0762943fe))

Here is the result for reference:
![headerrecyclerview](https://cloud.githubusercontent.com/assets/3116415/10208788/11322018-67d6-11e5-8ccd-a6c9d9368dd5.png)

Two things come to my mind:
- It might be a problem with your list of products, check its contents before rendering it in the recycler view. 
- Maybe it is related to the layout you are using for each item.

Try to play with those two things and tell us if the problem persists.

Cheers.

**Comment by pedrovgs** [comment] 2015-10-01 07:50
@everton15m can you review the library version you are using now? @Serchinastico has been reviewing your code and the library seems to be ok using the last release.

**Comment by pedrovgs** [comment] 2015-10-11 10:43
@Serchinastico can we close this issue? I've been trying to reproduce this bug using the code @everton15m sent us but I couldn't.

**Comment by Serchinastico** [comment] 2015-10-11 13:44
With no further information I think we can, we can reopen it if someone can reproduce it.

**Comment by pedrovgs** [comment] 2015-10-11 13:45
Ok. Closed.

**Closed as completed by pedrovgs** 2015-10-11 13:45 UTC
Labels: bug

**Comment by RockyLin** [comment] 2016-09-24 07:12
The header is missing after resume from background. @pedrovgs Thanks!
